### ISSUE TITLE
Under what license this project is distributed?

### ISSUE THREAD

**Issue by eclipseo** [Xuanwo/go-bufferpool#1]
Hello,

I need to package your project as part of the dependency tree of github.com/yunify/qingstor-sdk-go/v4 but you haven't specified under what license it is distributed. Could you please provide a LICENSE file?

Also if you could provide a short description of your prolect it would be appreciated as well.

Best regard,
Robert-André

**Comment by Xuanwo** [comment]
This project will licensed under apache 2 as described in https://github.com/Xuanwo/go-bufferpool/blob/master/LICENSE 

And description will be added at weekends.

**Comment by eclipseo** [comment]
Thanks!
